### PR TITLE
App Crashes in release version 

### PR DESCRIPTION
**Pull request by MaxToyberman**
NativeModules = window.require('NativeModules') is not correct , need to do it like this :  
var ReactNative = require('react-native')
var {
    NativeModules
} = ReactNative

### CODE REVIEW

**Comment by jhen0409** [comment]
Could you provide the error?

**Comment by MaxToyberman** [comment]
@jhen0409  please see my fix , this is the error : (caused by this version)  

ReactNativeJS: Requiring unknown module "NativeModules".

**Comment by MaxToyberman** [comment]
I have been searching for hours for the solution, an older version of this package fixed the issue so I realized that something is wrong with it .

windows.NativeModules is undefined in release version

**Comment by jhen0409** [comment]
Are you on \_\_DEV__ === false environment? I think [this is a reason](https://github.com/facebook/react-native/blob/5403946f098cc72c3d33ea5cee263fb3dd03891d/packager/src/Resolver/polyfills/require.js#L91), so we can just check window.\_\_DEV__, let me know if it work for you.

Also, this module should included in general JS runtime, so don't do CommonJS way.

**Comment by MaxToyberman** [comment]
@jhen0409  I don't use your library directly , I use reactotron-react-native which is using it . everything worked fine.
when you posted the new version it stated to crash.

**Comment by jhen0409** [comment]
Confirmed it's related to `__DEV__ === false` so it cannot use `VerboseModuleName`, I fixed it with https://github.com/jhen0409/rn-host-detect/commit/c196c41d6e32e306d406ddf1910f88b7f6369b66 and published as `v1.1.2`, please check it, thanks for the report. :)

**Comment by MaxToyberman** [comment]
@jhen0409 it works !! 
Thank you

**Pull request closed without merging**
